language: generic
sudo: required
services:
  - docker

before_install:
  # Build images to run tests
  - docker build -t aosmerkin/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run tests
  - docker run -e CI=true aosmerkin/react-test npm test

after_success:
  # Build production images
  - docker build -t aosmerkin/multi-client ./client
  - docker build -t aosmerkin/multi-ngnix ./nginx
  - docker build -t aosmerkin/multi-server ./server
  - docker build -t aosmerkin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push aosmerkin/multi-client
  - docker push aosmerkin/multi-nginx
  - docker push aosmerkin/multi-server
  - docker push aosmerkin/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-multi"
  env: "DockerMulti-env"
  bucket_name: "elasticbeanstalk-us-east-1-746258735500"
  backet_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY